[notifications]
environment = "dev"

[redis]
host = "localhost"
port = 6379
database = 0

[db]
host = "127.0.0.1"
port = 5432
user = "voicely"
password = "voicely"
database = "voicely"
ssl = "disable"

[apns]
path = "/conf/AuthKey_V66H7M2538.p8"
key = "V66H7M2538"
team = "7V2BB6PC84"
bundle = "com.triibe.social"

[rooms]
host = "127.0.0.1"
port = "50052"

[grpc]
host = "127.0.0.1"
port = "50053"
