[twitter]
key = "urQc0u9lRS42XN8J5njYOR3GD"
secret = "feX4xXuflmrnCPpgFCGptJiPEoxo7YsfTiznvhCJhoNm1yyXjBs"

[sendgrid]
key = ""

[cdn]
images = "/cdn/images"
stories = "/cdn/stories"

[apple]
path = "/conf/AuthKey_V66H7M2538.p8"
key = "V66H7M2538"
team = "7V2BB6PC84"
bundle = "com.triibe.social"

[redis]
host = "localhost"
port = 6379
database = 0

[db]
host = "127.0.0.1"
port = 5432
user = "voicely"
password = "voicely"
database = "voicely"
ssl = "disable"

[grpc]
host = "127.0.0.1"
port = "50052"

[listen]
port = 8080

[login]
email = false

#Birds
[[mini]]
key = "03ba569d-1577-43f0-8acb-602f0c2ca720"
id = 12

#Trivia
[[mini]]
key = "198ba444-55b7-47c6-8cb5-5cc912f83ea4"
id = 10

#Draw with Friends
[[mini]]
key = "349c0163-8049-4453-a067-aca72bb51254"
id = 14
